backend:
  name: github
  repo: neoconstructivist/neoconstructivist
  branch: master

media_folder: source/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - label: Method
    name: methods
    folder: data/strategies
    create: true
    format: yaml
    extension: yml
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Description, name: description, widget: string, tagname: h2}
      - {label: Text, name: text, widget: text, tagname: p}
      - {label: Image, name: image, widget: image}
      - {label: Light, name: light, widget: boolean, default: false}
  - label: Project
    name: work
    folder: data/projects
    create: true
    format: yaml
    extension: yml
    fields:
      - {label: Status, name: status, widget: string}
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Date, name: date, widget: string}
      - label: Methods
        name: strategies
        widget: list
      - label: Domains
        name: domains
        widget: list
      - {label: Description, name: description, widget: string, tagname: h2}
      - {label: Introduction, name: introduction, widget: text}
      - {label: Text, name: text, widget: markdown}
      - label: Categories
        name: categories
        widget: list
  - label: Pages
    name: pages
    delete: false
    files:
      - label: Intro
        name: intro
        file: data/intro.yml
        description: Intro text on index page
        fields:
          - {label: Title, name: title, widget: string, tagname: h1}
          - {label: Text, name: text, widget: text, tagname: p}
      - label: About
        name: about
        file: data/about.yml
        fields:
          - {label: Image, name: image, widget: image}
          - label: Profile
            name: profile
            widget: list
            fields:
              - {label: Title, name: title, widget: string, tagname: h1}
              - {label: Text, name: body, widget: markdown}
