backend:
  name: github
  repo: neoconstructivist/neoconstructivist
  branch: master

media_folder: source/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - name: methods
    label: Method
    folder: _methods
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Description, name: description, widget: string, tagname: h2}
      - {label: Content, name: content, widget: markdown}
      - {label: Image, name: image, widget: image}
      - {label: Light, name: light, widget: boolean, default: false}
