backend:
  name: github
  repo: neoconstructivist/neoconstructivist
  branch: master

media_folder: source/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - name: methods
    label: Methods
    folder: data/strategies
    create: true
    format: yaml
    extension: yml
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Description, name: description, widget: string, tagname: h2}
      - {label: Text, name: text, widget: text, tagname: p}
      - {label: Image, name: image, widget: image}
      - {label: Light, name: light, widget: boolean, default: false}
  - name: pages
    label: Pages
    files:
      - name: intro
        label: Intro
        file: data/intro.yml
        description: Intro text on index page
        fields:
          - {label: Title, name: title, widget: string, tagname: h1}
          - {label: Text, name: text, widget: text, tagname: p}
